-- Chris @ Machine Neovim from scratch
require("crs.options")
require("crs.keymaps")
require("crs.completion")
require("crs.lsp")
require("crs.plugins")
require("crs.telescope")
require("crs.treesitter")
require("crs.nvim-tree")
require("crs.comment")
require("crs.toggleterm")
