#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Launch Polybar
$HOME/.config/polybar/launch.sh

bspc monitor HDMI-0 -d 2 4 6 8 10
bspc monitor DP-0 -d 1 3 5 7 9

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a anydesk desktop='^8' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a steam_app_1147690 state=floating border=off
bspc rule -a particles state=floating border=off
bspc rule -a jetbrains-clion state=floating border=off
bspc rule -a zoom state=floating border=off
